[2025-04-02T01:25:25.820+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: covertype_workflow.train_models manual__2025-04-02T01:24:42.268554+00:00 [queued]>
[2025-04-02T01:25:25.836+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: covertype_workflow.train_models manual__2025-04-02T01:24:42.268554+00:00 [queued]>
[2025-04-02T01:25:25.836+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 2
[2025-04-02T01:25:25.854+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): train_models> on 2025-04-02 01:24:42.268554+00:00
[2025-04-02T01:25:25.884+0000] {standard_task_runner.py:57} INFO - Started process 137 to run task
[2025-04-02T01:25:25.898+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'covertype_workflow', 'train_models', 'manual__2025-04-02T01:24:42.268554+00:00', '--job-id', '138', '--raw', '--subdir', 'DAGS_FOLDER/covertype_workflow.py', '--cfg-path', '/tmp/tmpeertzt6m']
[2025-04-02T01:25:25.906+0000] {standard_task_runner.py:85} INFO - Job 138: Subtask train_models
[2025-04-02T01:25:26.023+0000] {task_command.py:410} INFO - Running <TaskInstance: covertype_workflow.train_models manual__2025-04-02T01:24:42.268554+00:00 [running]> on host fe42d0bc9f45
[2025-04-02T01:25:26.220+0000] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='covertype_workflow' AIRFLOW_CTX_TASK_ID='train_models' AIRFLOW_CTX_EXECUTION_DATE='2025-04-02T01:24:42.268554+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-02T01:24:42.268554+00:00'
[2025-04-02T01:25:29.700+0000] {logging_mixin.py:149} WARNING - 2025/04/02 01:25:29 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2025-04-02T01:25:59.549+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.9/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")

[2025-04-02T01:26:00.503+0000] {credentials.py:1124} INFO - Found credentials in environment variables.
[2025-04-02T01:35:50.592+0000] {logging_mixin.py:149} WARNING - Registered model 'CovertypeModel' already exists. Creating a new version of this model...
[2025-04-02T01:35:50.712+0000] {logging_mixin.py:149} WARNING - 2025/04/02 01:35:50 INFO mlflow.tracking._model_registry.client: Waiting up to 300 seconds for model version to finish creation.                     Model name: CovertypeModel, version 4
[2025-04-02T01:35:50.712+0000] {logging_mixin.py:149} WARNING - Created version '4' of model 'CovertypeModel'.
[2025-04-02T01:35:50.712+0000] {covertype_workflow.py:201} INFO - Registrado en Model Registry: CovertypeModel v4
[2025-04-02T01:35:50.772+0000] {covertype_workflow.py:210} INFO - Mejor modelo: extra_trees, acc=0.8555077452667814, stage=Production
[2025-04-02T01:35:50.773+0000] {python.py:183} INFO - Done. Returned value was: None
[2025-04-02T01:35:50.806+0000] {taskinstance.py:1368} INFO - Marking task as SUCCESS. dag_id=covertype_workflow, task_id=train_models, execution_date=20250402T012442, start_date=20250402T012525, end_date=20250402T013550
[2025-04-02T01:35:51.153+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2025-04-02T01:35:51.205+0000] {taskinstance.py:2674} INFO - 1 downstream tasks scheduled from follow-on schedule check
